spring.application.name=my-biblioteca

spring.data.mongodb.uri=${MONGODB_URI}
# mongodb+srv://marlon1906ia_db_user:ySSODWQS5rqbgoSZ@cluster0.jtyfern.mongodb.net/biblioteca_db?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=biblioteca_db

server.port=8080